[window]
opacity = 1

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# One Darker color scheme
[colors.primary]
background = "#1e2127"
foreground = "#abb2bf"

[colors.normal]
black = "#1e2127"
red = "#e06c75"
green = "#98c379"
yellow = "#d19a66"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#abb2bf"

[colors.bright]
black = "#5c6370"
red = "#e06c75"
green = "#98c379"
yellow = "#d19a66"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#ffffff"

[keyboard]
bindings = [
  { key = "Return", mods = "Shift", chars = "\n" }
]
